title: Orchid Chetia Phukan # your name (or website title) here
logo: "/images/Orchid_mosaic-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  I am pursuing my Master's in Data Science and Machine Learning.
  My area of interest includes Natural Language Processing, Geometric Deep Learning, Computer Vision.
  <br><br>
  I am currently a Research Intern at Artificial Intelligence Insitute of University of South Carolina with focus on NLP and Deep Learning.
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
